---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: neutron-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgBmn8S4xTOv6JjX/OCpEAtfIp3f8eQS5qF+iTNQIb3XvcC3d9Xc24AN2kCaA3/p0S2Hn9gLPGFmWz7V2xl/MeMnr7Mq2jGuXOijUn4wKbhSDQd8Vh69zJ1E4x/nKcEGFii/F8WZhU2oJ/b5GOR4D5Odl6YqGmtwFNvh0/qfqiRhuP5IWy1L0uY00NPah2fHQmIdfg3zGGEd9FTukV6rWuXFpsg8dS/r9dxZsj7kbK+YOTQ0rxhd0EfhDPu4aZQrMkBrNqVajfG+HYCW6DJpJcqcL5dJKzW0SbcWvTbQfEQO4mWMrKWxytDDHpJrRB0Fdi0SO9vlQzgD7OHJODSH4iibAdd9+0Rz2Xa53fMFyxz7nRpJKnxP24inyG6G3P/kcRNCTPAOoosI8Dd6jTPIgFa18LytrTH6Wys0IDg5hKHJH5YJwwaDHdztgO6xAQcj6TkizpcoqMuD0m9EvVGYE/d/86CGq/XyxxPG4wUGTF5YkaIYFR6eDYXySGH0pfFUEfc8QbVfUSWAozkvjXdu9dHnTnE2zk51E48uZ7WibsQ0brs7KV2PFte85fDUb9hgV3wmzrU7XQzf8HcJ5+KfmlmtNBwJnWRq8b1b8l7Sw3rkViAfptaj47RJWlC6ZEyYeXdjAMWQt2E2za3UbfN6uy1W9XP/RCX10q3tdu0g+kOvVMcdCXyn/tjm6Ajy6paHDVcOlhydwHI2e0Jd26bNwS8JmjygHujRDyVEa7EeYIyIhw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: neutron-db-password
      namespace: openstack
    type: Opaque
