---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: neutron-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgAfusPKoIhcS1A/F+voLXCfIvvxOgVxykSTb/yoaKYsYN1SeIjhuBZCO+14J9cxvH92q+JcOncksUPqDYdU+JL1cjkz3pq36rolYCPXjKVCPuVPJAIgBmVLRo/PITwATYDgwDYfFICHwjCnxAv+9o5y8etP0cWY8Dpspy1tqFNOWB+ULtSKf3eiAZVzA31an6jvBkUrjH5LdWHruCO9hO6Vwr91ERMZuFYq/9uGTmHHinX2mqFZE1grR0wGHFAgkEydDfY7v/e+YAXa/1QKyCBzGRGCd+5gHy3LackLnyjzcD5VVoMaQzTocteVwQZsXhfqbXtNQmCNV8NnDnOmkXUz3+WmRHP1UERFKEZhdQJMGxVeFSwLPlC9+OvBA3unM6W7Ewuu9mEJGnAd/7p2CITO3Wm9dwKM2A0vEX9VwEaxkD8js81+J5dnIlra3rICj7/jSBfbRrG9exydUvvJBQqJgFEDkywUTQqRQtRs/CwZ/we6O3oSVc97IyeZppOt8tWZLxYLwfh1ImonHAFJU192EjLYFMeGTJkg/0Dn0Yp0D4Z0LtcVTot9+MPHlMYKZgVwlhCzRScqxyCvceGdZwsNkDiIq+3AHMphvmD4KAWUopabwu/wlVRbfaEfk3pu/rFxSRW+FDNKOJLYQiy5AZ2clln/kKvj/X93GfnvvuUTvaDv0Q+hCnMLgofEZWx2r5bPBmXmtPEOc6gCqshTlXDy3BLWB0W9NB+i0Saa/VNyaaAqFWgUx5p+uWw4CgSshTZDimHkc+cVV1KJ+rcEqCQa
    username: AgDB1q/AbxB+ty+HRobSd3gkSNwi/MnsbPIs7j1hXNhZiOXeM/Thof4WoH/fkCE2OMO6L3q+NBTg7nKe9c5tX0fRZsIWMYcaOIQ6XnuWOuaaH5LaPXxylMXpsKyPiHor1Kz+I+XX9t621QTrTIXKUniRT6a6pDx5oM04PlAXFVsjfYgbBA8EVlwM7nSkEXipX/fF9OCihFFzxsBZsH3pBx4mHGjCbTn+lXxSQNCgTkNJ6HaVR5gNCjD63Bk2wZoK7j23hw1K431e2moS4F6y7yZ5OdOrWR9T6K3QNdMkTGJ3MKpK9kYnC/Xyvk+I9HZ3L4ynUB0sU3NTakZhvcgf9PLi9bDts0YQj+n7smDi00eCRn4pkL0AVa48ZC3zBvDgl5MiXqzC5ffYLzZ2NM61i5h0HqimXNBcsFpB/9ZHLB6Wb1ZzT3fiElm3bVw/1U3Lhx6s/P7pmMQ5GbjX72IPJ3bG6rwV4Q+NQ/a0CO6sl9TdlqyXVz+5XQR+x4sljaxVWDepB7+44/uci9i00tPYp+AF9ALzwLbXNJV4wxVKLtEAdWobGovtaWod8mDK7M95wJO8LDfSSSqJBUIWo2rLvZJXU9z9mZmjcC2YAoGddAWi18oQNFGL1I1anA+2NCaCVNHdBYvAtFwR8iIwTPgGXcEQWIlwplkF6JOS/FThrmB/Vq2mmt++/db4UJCF+ZsuyA/tiVUxBZbt
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: neutron-rabbitmq-password
      namespace: openstack
    type: Opaque
