---
# Source: nova/templates/cron-job-service-cleaner.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nova-service-cleaner
  namespace: openstack
---
# Source: nova/templates/cron-job-service-cleaner.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nova-openstack-nova-service-cleaner
  namespace: openstack
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - services
      - endpoints
      - jobs
      - pods
---
# Source: nova/templates/cron-job-service-cleaner.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nova-nova-service-cleaner
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nova-openstack-nova-service-cleaner
subjects:
  - kind: ServiceAccount
    name: nova-service-cleaner
    namespace: openstack
---
# Source: nova/templates/cron-job-service-cleaner.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nova-service-cleaner
  annotations:
    "openstackhelm.openstack.org/release_uuid": ""
spec:
  schedule: "0 */1 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 600
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        release_group: nova
        application: nova
        component: service-cleaner
    spec:
      template:
        metadata:
          labels:
            release_group: nova
            application: nova
            component: service-cleaner
        spec:
          serviceAccountName: nova-service-cleaner
          securityContext:
            runAsUser: 42424
          restartPolicy: OnFailure
          nodeSelector:
            openstack-control-plane: enabled

          initContainers:
            
            - name: init
              image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
              imagePullPolicy: IfNotPresent  
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsUser: 65534
              env:
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.name
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
                - name: INTERFACE_NAME
                  value: eth0
                - name: PATH
                  value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
                - name: DEPENDENCY_SERVICE
                  value: "openstack:rabbitmq-nodes,openstack:mariadb-galera-primary,openstack:keystone-api,openstack:nova-api"
                - name: DEPENDENCY_JOBS
                  value: "nova-db-sync"
                - name: DEPENDENCY_DAEMONSET
                  value: ""
                - name: DEPENDENCY_CONTAINER
                  value: ""
                - name: DEPENDENCY_POD_JSON
                  value: ""
                - name: DEPENDENCY_CUSTOM_RESOURCE
                  value: ""
              command:
                - kubernetes-entrypoint
              volumeMounts:
                []
          containers:
            - name: nova-service-cleaner
              image: "docker.io/openstackhelm/ceph-config-helper:latest-ubuntu_focal"
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: 2000m
                  memory: 1024Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
              
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
              env:              
              - name: OS_IDENTITY_API_VERSION
                value: "3"
              - name: OS_AUTH_URL
                valueFrom:
                  secretKeyRef:
                    name: nova-keystone-user
                    key: OS_AUTH_URL
              - name: OS_REGION_NAME
                valueFrom:
                  secretKeyRef:
                    name: nova-keystone-user
                    key: OS_REGION_NAME
              - name: OS_INTERFACE
                valueFrom:
                  secretKeyRef:
                    name: nova-keystone-user
                    key: OS_INTERFACE
              - name: OS_ENDPOINT_TYPE
                valueFrom:
                  secretKeyRef:
                    name: nova-keystone-user
                    key: OS_INTERFACE
              - name: OS_PROJECT_DOMAIN_NAME
                valueFrom:
                  secretKeyRef:
                    name: nova-keystone-user
                    key: OS_PROJECT_DOMAIN_NAME
              - name: OS_PROJECT_NAME
                valueFrom:
                  secretKeyRef:
                    name: nova-keystone-user
                    key: OS_PROJECT_NAME
              - name: OS_USER_DOMAIN_NAME
                valueFrom:
                  secretKeyRef:
                    name: nova-keystone-user
                    key: OS_USER_DOMAIN_NAME
              - name: OS_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: nova-keystone-user
                    key: OS_USERNAME
              - name: OS_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: nova-keystone-user
                    key: OS_PASSWORD
              - name: OS_DEFAULT_DOMAIN
                valueFrom:
                  secretKeyRef:
                    name: nova-keystone-user
                    key: OS_DEFAULT_DOMAIN
              command:
                - /tmp/nova-service-cleaner.sh
              volumeMounts:
                - name: pod-tmp
                  mountPath: /tmp
                - name: nova-bin
                  mountPath: /tmp/nova-service-cleaner.sh
                  subPath: nova-service-cleaner.sh
                  readOnly: true
                - name: etcnova
                  mountPath: /etc/nova                
          volumes:
            - name: pod-tmp
              emptyDir: {}
            - name: etcnova
              emptyDir: {}
            - name: nova-etc
              secret:
                secretName: nova-etc
                defaultMode: 0444
            - name: nova-bin
              configMap:
                name: nova-bin
                defaultMode: 0555
