---
# Source: nova/templates/job-db-sync.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nova-db-sync
  namespace: openstack
---
# Source: nova/templates/job-db-sync.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nova-openstack-nova-db-sync
  namespace: openstack
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - services
      - endpoints
---
# Source: nova/templates/job-db-sync.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nova-nova-db-sync
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nova-openstack-nova-db-sync
subjects:
  - kind: ServiceAccount
    name: nova-db-sync
    namespace: openstack
---
# Source: nova/templates/job-db-sync.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "nova-db-sync"
  labels:
    release_group: nova
    application: nova
    component: db-sync
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-4"
spec:
  backoffLimit: 1000
  template:
    metadata:
      labels:
        release_group: nova
        application: nova
        component: db-sync
      annotations:
        "openstackhelm.openstack.org/release_uuid": ""
    spec:
      serviceAccountName: nova-db-sync
      restartPolicy: OnFailure
            
      nodeSelector:
        openstack-control-plane: enabled
      initContainers:
        
        - name: init
          image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent  
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: "openstack:mariadb-galera-primary"
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            []
      containers:
        - name: "nova-db-sync"
          image: "docker.io/openstackhelm/nova:2023.1-ubuntu_jammy"
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: TRANSPORT_URL
              valueFrom:
                secretKeyRef:
                  key: TRANSPORT_URL
                  name: nova-rabbitmq-user
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  key: DB_CONNECTION
                  name: nova-db-user
            - name: DB_CONNECTION_CELL0
              valueFrom:
                secretKeyRef:
                  key: DB_CONNECTION
                  name: nova-db-cell0-user
          command:
            - /bin/bash
            - -c
            - /tmp/db-sync.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: db-sync-sh
              mountPath: /tmp/db-sync.sh
              subPath: db-sync.sh
              readOnly: true
            - name: etc-service
              mountPath: "/etc/nova"
            - name: db-sync-conf
              mountPath: "/etc/nova/nova.conf"
              subPath: "nova.conf"
              readOnly: true
            - name: db-sync-conf
              mountPath: "/etc/nova/logging.conf"
              subPath: "logging.conf"
              readOnly: true            
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: db-sync-sh
          configMap:
            name: "nova-bin"
            defaultMode: 0555
        - name: etc-service
          emptyDir: {}
        - name: db-sync-conf
          secret:
            secretName: "nova-etc"
            defaultMode: 0444
