---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ironic-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgCJJefaQ6on63hUTzBHBlYI7BPFbMVgl6EUUkKdnkPpMhx+M2/9IrpGAcM4Q6j7KCYCMwiE4+S4Kvg1O2NODGVQyNetha06Su/TTpzk/IE4a7a05JFA9H2urQUaK3MmkrB7DopGAqG2+175X5iGWQwSkQNetpz6hfSwDuH8sSo7Sa5XmeL/KbHyUS+Ye8RKCKaGp0ORUOZQ4zJubLIv2l4xi4a7NE12mFAmuXnVqeGHWvwcHCuMB5iDaWugL1bNTzKEHT53xfQgcN68sEaTHABR4NOHbfnrWkkqmIZ1oIAKqwU2HyEX3NOA+mDRCsFLOmxHCtaM7hPkaMq0Gj/7lSRCre6mB+0D4/eRAGyWz+3QIzVEgHkXvigtjDr1ULucCh/Z3I7+EzUoWM7aLcgZxsjDyshNY1iUaKWMuhWy9bb72EM7iVdMjdp4rjd3X05N1ok9oYKD2puANnD3EVULLIEfaDhSxny/TkH8o66e0Ea+Mo6q96X23tWg/q48lTbCocMxFmuWP7OB6FZwBlsPfsFtdHYSkJwzyeW5e94eumq2ZJc+0BtUQy1zpsCRSJL81+eAzeBLSr4JkRJ1MvVRug9hMNrwjnAm2avlhn/mpAvqBnsuxyXlAJ0M3rOcyLN+jMKoLSpD7cEc0IMlKTAUF8B8fSxeG1B37nvZWdYhONW/j7EF5ahaay32XFefu7djV+0Svdehfb2GUdo8SBTncHv2xxLyoY0EFEXrGx56u0CX+w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ironic-admin
      namespace: openstack
    type: Opaque
