---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: placement-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgBhkvRK4qE2X4SrpT8MWKhYYTcAe70IXFORDPZ3/QPw/ByyLOUhF1j/VeTEqMfGjhB0nR7G7c75GiLs6J11cjIdgzBMLiAUBcDPlA4aAWC/3r0v5VrRSzg4ET2YirC+8w6xzocxfM6vZ9A58M6vn/T/wwTt3k8JJGoTnKueg53SdzZPYf2KxOem69KvMpZj2VZyhVHnbFOHTxHvnXJG3arLczU1GYsAcI9BsaDEhN1duQAGWcpRO7TRjQr3NDgbSXvfOgyebJh9fE5t73Q35C2ACIooT2GqIRX1p6tMVpEPFaoM4GCNpLpE10SwFBY1/qIzxCKo5/mLWwhqMd5nlyChyZVsJ8PEUaWZbnzAptXIv6jIlC1YiH0zeOwdOfpdLn3Rj9lvv9ENAKxQmG3rG0MnyGpczGnz5woex8VmTZOFgK7+chFrA0QyCHGIYpHEeOoCksoTeK03+y+hQRr6DktGdGBV6tGNqh1hrLCX2mSNtEthj1i3Z+v4Sh35k34ovOTCTwiizi4qB8UDY38iDoOJt7NLLhZXB3bv805bjo5UUg0hp4USJiiORIKAguFL3upLNqqCJs7RXadxf8ASJTOB8mSEfbA/X2/NnPruugQb6hSdwmAvZ9enCW4OIWZlf1886Y593N1E3C6U7MGIev7CrS1pK0pL61CUhEP0kJs3h5HWS2cXI62PfVkig13VLirF9c6LLpHahhO/CZfx814chhkF5ik2tfO7pELbnh2X5g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: placement-db-password
      namespace: openstack
    type: Opaque
