---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: placement-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgBESX0/1tInp4hOSdaLlP1oQgnaJxos7RVMncheDSAArNHrZE11suAyOd2iZemSYe6w5qA8U99GXxZlrgvfAWdzL6lhl1prF+V29gbNytaK3C2hGODqp4HC0HdMY73ExPQ01uuAIBVF1H2/uBFa/bOpPhIW5uFsXf+r3D/CVTegV6FskNha5gyBak7P28uwLK0v5dTE31J/slB3T9yJfJQ3qaWxEc/77eVTyeGeA1sLOJKddabQhAyMgEuM7VCXzSxPLEFdcB7xPz5TjONdFemLLtMqnUEIJECa2OqpcC1ZN9KixHortOxmZhWIoq6/OKshYbDmQd+I5CnMIZ1/YoQVKb0itraL5tDh3zxmKDDUDDaokJ1vAxK5jovaB70iYpUeEBUmv20KeSavdmdnCgbf/+aLJSx0kszUW2Qshb9sFqA0mWjYDg4nFmhodI7aXa9LUvQv3MwT8lxcga+OZkVoVDRnP1dViu9J8iSgj2OZtWeZHk42/CEJyw0+SJeL/wpL/hg+As9hnWGI4rjzu9eMOMBscZxqxZIHcbRQnMvWMauI5uwhpnY9hhvia29wnbyS3/IM737UW/hOT6Rzk5TrCxrzjRziTo7RoGkRcBmj1BEp2r8sPcpHI0QENSvuG3lV4eGQsJJA1qKBqa6YmGLh24BQJbv3SLO6VVNPR6p37R46A5kNERjLXpm5Yzcrb0RchdfTYINGaFxb8lkSk1D0UokCegtbYRx9Kx2VaNoHQg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: placement-admin
      namespace: openstack
    type: Opaque
