- name: Deploy RKE2
  hosts: all
  become: yes
  vars:
    rke2_ha_mode: true
    rke2_api_ip: 172.22.220.24
    rke2_download_kubeconf: true
    rke2_additional_sans:
      - rancher-server.pbandark.com
    rke2_version: v1.26.11+rke2r1
    rke2_drain_node_during_upgrade: true
    rke2_cni: none
  roles:
    - role: ansible-role-rke2
     
