---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-rabbitmq-admin
spec:
  encryptedData:
    RABBITMQ_CONNECTION: AgAfyb5aROSRrf0B6q4iW9fNBowDt+g6io7hWBGP2dKwpsznI2Wy2VKltajTuqHYpaP0f99DZ4QMq0NU5mHXvIP61EPRXgIwk5w0XAhCJXLj+5Hx9hztB6E2bfa8wL0/v7Ak1SvR2fmZfGH186aS+FbxFKkxRDTjF26lrhQ4hBfHHapvfU5nrAU0yK/zxPeR9QHWi9JUT88G6XNN3DdKDwltkx+IpKk1fVFFQMY3ehQg3M/ExgUrPlS2ifxCAwDS7yrH4yfsN/5IlhLI4i8DFshUc+llrMLSVlLxY7sKKVZ+ps8/PIldG00gagqrvETFFFiKeDO+zT1lk/OQC1T5lY05lV3sKatslom6a90dyxJwDRmiI3/s/mnrt2TLrnZNy0OFgnB1pF0Zczbh4HU0YRE0GAfNCJzREigAZPG7Uj2YzKr3acMl2f8q6j+xRqonMOP3qOQny5bXxxgHt5hfxQ6H47Tnjseb8CPHgUBLz6H4ImAXiLfMkEOJ42IVmsYE6kGAxrEIzrLloqs+FQnhD8roaD9HQG5NV+4ZMneSY2YOHVRfMI0y9kFBmUubUJn6U0ZE8WLpZjo3px4tSaTeGS/tkNZFC+lfqbxI8p4qpkaNWsCNtAdCmpvx+0QVuFr+VZNAFD+CjlcKufbDNMzqswt5BgS3ZagHooQcrmi2vxVO8LViGvGKPDBA4kkYFDoIZ+HTFVzo/HpwbpQaCAh9gCESsPlW8c2JPqSq34R+bCJeATO6t0tS3eoEYdhKi2OXh74LY78c5wQ5KQd70pTgnCbUPL8AmQbwLmJ48sdy7R7C7utxaTsRXCWfFQk/2qsFK+BqHYaCXGQ1ZVFCdbU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-rabbitmq-admin
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-rabbitmq-user
spec:
  encryptedData:
    RABBITMQ_CONNECTION: AgDDQLYdVdKvSx2Sl8Bi/NDevFGqcZCxl71v46Loir3dn7Xbyf2MENd48zG2w8jchI+FRxjKFleI0RJbEmJqARY0ZCWrjS8y5xVQZi4FlTsiDf7JjAlixMChYMzLlovpX2HgbWgKBVLOk2KCKrq9QXYdEMJ8S1of7yY1N4ZGBy7lYNOBm7PVgrfELa61jQPzHTeko2QsgMTxon0aalOqlTJ0UP9i1pbHK221ztqa7Z2ZWc5LEBAnPvone4BQx4TJlwGUDjgTirlgnuMBBKDxGh+5GqNGCzKSOGnB2rmszNGMp/HmEU/INMIKaOOhGJGwHPccrEXyLazJW57nFQVS3gZb3/UEek23LEHjVhbhDBtvAZYWJRdOvCgKqN/N4eWHpKZ4EnVEDIyf7QyBWb5C6kYDjcmONU9smjEMtzfg8t96eakIQMKY1EXud8u2aexl0OmB53nzVXpacBZp0zB8CJlD3y99YZbYBGIwwRn/asrBSf76fHutyY8sO4cZeT9NIILnLJLpTpvxWcIL+DkkBRcn31GFqRbtq2L7oq3Zbz3bvOIBRgXQ6I0Bs7MxxxE1MA2O/q+wRy2b3KxRClB/aiL8AwPAUp/jwgDaYFuQpRs9giwU6+HT+WZGPdlVOReRxp2dUS5ZlSPZtRhr2sjibJZK7M8c/GSRr7KdaxSL4jZUw9FIpn6O9n1TPcdGVDX3HbJDRpkgI/0xnwQiEKbIItFXSxRxn3QBLWWDek7hHN3h9OO0LrSGPHKbCNl/I0R+eIqVP7okWjJnrX8kmhXICZPjYWwDSftdT21lsCRYOfejYU9xHIzojGxePknDvviEcyiHvlnCVaWTaN1pp8emnOkic/UQA6O4yrJsZVNAVdGYJN00vL6GtRXx5H2fvw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-rabbitmq-user
    type: Opaque
