---
# Source: keystone/templates/job-domain-manage.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keystone-domain-manage
  namespace: openstack
---
# Source: keystone/templates/job-domain-manage.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keystone-openstack-keystone-domain-manage
  namespace: openstack
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - services
      - endpoints
---
# Source: keystone/templates/job-domain-manage.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keystone-keystone-domain-manage
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keystone-openstack-keystone-domain-manage
subjects:
  - kind: ServiceAccount
    name: keystone-domain-manage
    namespace: openstack
---
# Source: keystone/templates/job-domain-manage.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-domain-manage
  labels:
    release_group: keystone
    application: keystone
    component: domain-manage
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        release_group: keystone
        application: keystone
        component: domain-manage
      annotations:
        "openstackhelm.openstack.org/release_uuid": ""
        configmap-bin-hash: "3893cba6daf98f87b5895960410d2320d2eb5f67c632f6017c90318bac1a9d29"
        configmap-etc-hash: "9c1f9e27f0491fe276786e436323e62342df5ae809b5f5c73a2274bee473371e"
        
    spec:
      serviceAccountName: keystone-domain-manage
      securityContext:
        runAsUser: 42424
      restartPolicy: OnFailure

      nodeSelector:
        openstack-control-plane: enabled
      initContainers:
        
        - name: init
          image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent  
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: "openstack:keystone-api"
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            null
        - name: keystone-domain-manage-init
          image: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
          
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          env:            
            - name: OS_IDENTITY_API_VERSION
              value: "3"
            - name: OS_AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_AUTH_URL
            - name: OS_REGION_NAME
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_REGION_NAME
            - name: OS_INTERFACE
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_INTERFACE
            - name: OS_ENDPOINT_TYPE
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_INTERFACE
            - name: OS_PROJECT_DOMAIN_NAME
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_PROJECT_DOMAIN_NAME
            - name: OS_PROJECT_NAME
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_PROJECT_NAME
            - name: OS_USER_DOMAIN_NAME
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_USER_DOMAIN_NAME
            - name: OS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_USERNAME
            - name: OS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_PASSWORD
            - name: OS_DEFAULT_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_DEFAULT_DOMAIN
          command:
            - /tmp/domain-manage-init.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: keystone-bin
              mountPath: /tmp/domain-manage-init.sh
              subPath: domain-manage-init.sh
              readOnly: true
      containers:
        - name: keystone-domain-manage
          image: "ghcr.io/cloudnull/keystone-rxt:2023.1-ubuntu_jammy"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
          
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          env:            
            - name: OS_IDENTITY_API_VERSION
              value: "3"
            - name: OS_AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_AUTH_URL
            - name: OS_REGION_NAME
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_REGION_NAME
            - name: OS_INTERFACE
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_INTERFACE
            - name: OS_ENDPOINT_TYPE
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_INTERFACE
            - name: OS_PROJECT_DOMAIN_NAME
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_PROJECT_DOMAIN_NAME
            - name: OS_PROJECT_NAME
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_PROJECT_NAME
            - name: OS_USER_DOMAIN_NAME
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_USER_DOMAIN_NAME
            - name: OS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_USERNAME
            - name: OS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_PASSWORD
            - name: OS_DEFAULT_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: keystone-keystone-admin
                  key: OS_DEFAULT_DOMAIN
          command:
            - /tmp/domain-manage.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: etckeystonedomains
              mountPath: /etc/keystone/domains
            - name: etckeystone
              mountPath: /etc/keystone
            - name: keystone-bin
              mountPath: /tmp/domain-manage.sh
              subPath: domain-manage.sh
              readOnly: true
            - name: keystone-bin
              mountPath: /tmp/domain-manage.py
              subPath: domain-manage.py
              readOnly: true
            - name: keystone-etc
              mountPath: /etc/keystone/keystone.conf
              subPath: keystone.conf
              readOnly: true
            - name: keystone-etc
              mountPath: /etc/keystone/logging.conf
              subPath: logging.conf
              readOnly: true
            - name: keystone-fernet-keys
              mountPath: /etc/keystone/fernet-keys/
            - name: keystone-credential-keys
              mountPath: /etc/keystone/credential-keys/

      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: etckeystone
          emptyDir: {}
        - name: etckeystonedomains
          emptyDir: {}
        - name: keystone-etc
          secret:
            secretName: keystone-etc
            defaultMode: 0444
        - name: keystone-bin
          configMap:
            name: keystone-bin
            defaultMode: 0555
        - name: keystone-fernet-keys
          secret:
            secretName: keystone-fernet-keys
        - name: keystone-credential-keys
          secret:
            secretName: keystone-credential-keys
