---
# Source: keystone/templates/job-fernet-setup.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keystone-fernet-setup
  namespace: openstack
---
# Source: keystone/templates/job-fernet-setup.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keystone-fernet-setup
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - update
---
# Source: keystone/templates/job-fernet-setup.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keystone-fernet-setup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keystone-fernet-setup
subjects:
  - kind: ServiceAccount
    name: keystone-fernet-setup
    namespace: openstack
---
# Source: keystone/templates/job-fernet-setup.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-fernet-setup
  labels:
    release_group: keystone
    application: keystone
    component: fernet-setup
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        release_group: keystone
        application: keystone
        component: fernet-setup
      annotations:
        "openstackhelm.openstack.org/release_uuid": ""
        configmap-bin-hash: "3893cba6daf98f87b5895960410d2320d2eb5f67c632f6017c90318bac1a9d29"
        configmap-etc-hash: "9c1f9e27f0491fe276786e436323e62342df5ae809b5f5c73a2274bee473371e"
        
    spec:
      serviceAccountName: keystone-fernet-setup
      securityContext:
        runAsUser: 42424
      initContainers:
        
        - name: init
          image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent  
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: ""
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            null
      restartPolicy: OnFailure

      nodeSelector:
        openstack-control-plane: enabled
      containers:
        - name: keystone-fernet-setup
          image: "ghcr.io/cloudnull/keystone-rxt:2023.1-ubuntu_jammy"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
          
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          env:
            - name: KEYSTONE_USER
              value: "keystone"
            - name: KEYSTONE_GROUP
              value: "keystone"
            - name: KUBERNETES_NAMESPACE
              value: "openstack"
            - name: KEYSTONE_KEYS_REPOSITORY
              value: "/etc/keystone/fernet-keys/"
          command:
            - python
            - /tmp/fernet-manage.py
            - fernet_setup
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: etckeystone
              mountPath: /etc/keystone
            - name: fernet-keys
              mountPath: "/etc/keystone/fernet-keys/"
            - name: keystone-etc
              mountPath: /etc/keystone/keystone.conf
              subPath: keystone.conf
              readOnly: true
            - name: keystone-etc
              mountPath: /etc/keystone/logging.conf
              subPath: logging.conf
              readOnly: true
            - name: keystone-bin
              mountPath: /tmp/fernet-manage.py
              subPath: fernet-manage.py
              readOnly: true

      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: etckeystone
          emptyDir: {}
        - name: fernet-keys
          emptyDir: {}
        - name: keystone-etc
          secret:
            secretName: keystone-etc
            defaultMode: 0444
        - name: keystone-bin
          configMap:
            name: keystone-bin
            defaultMode: 0555
