---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: octavia-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgCQyK17OmaqAOwqX5dnI+46tSVqLCd6czqPErIi0kfjwgQGyCavP2kuHYUub7YbF/P866YoH3X2HKX9A+7D9CZavjnW4yQ1ZpxVlU4b+eu1VxN6Oc7LtB0qa0ogowsmubaOjAXsGbV8phAF8h/I76dbwNtam6TxP190xa+Hx5QdQPDvdNtilQoEPNEbf0b/7iuezT8FEh+2Z2XFocxN7DLrE3RyJI5zTbi0DD2A11tbbF5IIlHREMUg4HgcPymExKeQCL3WutNb/clTgcZhoWbNcGO9T+muJjmDjEnhZkqiIW03uDkbeA629F49j77O+PNhsIEaje86aEqgv1e+k2irnpbnCKkAwVkappVyztKF5fbplsjcck7zDdfANsZajqLa1Vgms2JF72s3jSDVFPdrFhOlVgNhqAOINPjH8A2RrtE9dO2FmP1+XJokisvJAZCZDTKvFRSxrYyG61Q2EB5Y3a/3Lw/bz0j05VIgLG8o5d37tZaAke8sg6vdXkkMDmbFCl6LaCD0U+ZNF6m3ILjybVQDDQooeUu7bp7gRiHloo9IvgwG7iXvo8CSOyA/Eqtg4tHxW58c0ZPj12Lsvihu8uFYCqF1EuwtddG4EegFdlFsu7s+vpq3xjiB3YUmaM0PIQQN76hxQop1vRZZYXWH37ZTk+lR3tIbmFETkntKw2YnL69o/MyTYpivF03KzMYW7lqeetB0Hjx8Ht4QJvtxA4GzWXyzxW7QqdYzvDNUFw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: octavia-admin
      namespace: openstack
    type: Opaque
