---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: octavia-certificates
  namespace: openstack
spec:
  encryptedData:
    password: AgCsqlskrcTDUKczx9E+nNJDD5SVVNhJ9rc/lzu/Zu3O18TxYJKId3OW9jKEdTj6rojMXPLSOvS3WuO+mXXr61bg4Me3Pq6z8nZxYDWl0IV+bEJfrSes3VJERXEteEwLfb0+xmF5A7qWyLgc/RQmT7m+/hnKYQx8A59R7bbuVyCSByxof/ED/mEeH7isgpvhyI6Yjq6u6Jdwx3B1t4N7r69yFc5v3qjOOSyP+bk2NKuMqCpjle508b4MKY4Hg2vWMWXkZqLRkMuGCwk9rHz/IASEdgsx84HkHtBXfL91azqZCuVZ1Z6Wr8T4KA/RY28l57ixDvIptzg+eHvskTxm21phVTs09eDGfqyQNCN8h013cFZyYVqizRZ5oW+MVMO63/q5lRwVVfux43Ceqar/dNZH7mK3EPmGlLIHRNOQTy8waRYfxEHmdiy75SwElxc6O0d5n5tfJeARhFGHI86feKk8ATkVCcBoAlus+HKwBG+QxkdOyMU4yqNLZKjzGlPAudKsRNCk2gKnF/FiJEhmTuxiGx+BkXw/vgaJz+nIMZvYXR1g9+jM2aybTNs5qI6NiIMTEM43EaoSKufWkLSRcg0dFI+2agKuasUh0TtQLI4zBzvFdXqIcU2ZXx5iQkT1cBfra3eqpfnNIdR1vTaBHzUVSqHF5HvPXgATY+2TqFGCXhN6jAUD3gHhcbZKnqvaopPhGajAhTrjUkcrbSgNwAqVA3MZpITw0J7sUb7ycick/w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: octavia-certificates
      namespace: openstack
    type: Opaque
