---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: octavia-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgDEnm3dj3+Ok1pdj3uPLnFvw7OEEAaUpry36zwpAMwscYPv2d5eVpp3Nuc7VT5znZnGfmUWMqBXkRYLNQp2Mbjla7krbFUK0tmx6qWn6wmRiccXYuwQBLyzQVnP1lLQS7IugwK9vWg9UhHPjqzxAF0/FujFMOu2CooTwVqGQtNFCD3GxjaX7nRwnAfbzfExfHbz+Bdq1/NHR/UEa4Qmsjl20pZsmqSLkLBIWKoyZlM5vMDImvWtlDRgeECQeHVL7LSX8ppuQpyL2AzxjuswO4MvIv4rlmRZ8gZx14yEqt0KY2l3o3DFZ7uh/FubVvIdnYz/HSj7JZSh+c+A1tQjYiY4J5UabO4bzZ0k9twb9J5NhldLff4byO1tkwwp8wmK6xyrcvM1nGOYTR+2Ivk8f9pIgMWa1z7EsjabMDwbBaBBi6/8z/XVCFEF2Z2ycpzdAcBvc2/Svbl2O8mBPdoAZyQrzo4yM+z8NCJVWax5K15reYogzVwgi72sX+so16yrEPKhRBJcP1sFFgChT1j01CbphDSYDZ9QU/o2I4E0NZ2bfhV3dEJa49RZwoHhJQSpIcYFvUNQIjmIrWED8DT83hI72rFX6OokSUuacrRcFcgWJNQzNF/Ikp9VNrxw9GgxD05mVbdxSoqiv+30HOks8+azge6lu0qu4t8MQVApHExN8UZgL+QXszCAGf38Cm8ZFtsfaAt01caX48970zS02Br/Bqp1FC0u09v8IjjUf4svphkhqNdjfGDy8p0q/6+nUxo22ridkwN8QSvvgOQtKXsq
    username: AgA65wGVsA9NriAUkMsds+Eb24CNkuAbeCSZCJIzXNkJJHTxacD6VYbxRb/F8J6AnKrp8g8023UDQq8fjbttuD47nL32xMa61Po5pMnt0Eb6Lz96ZqN45+tc6qDNJBd0TN9UqyG9REew9E1U7rbn+huygqNWqcQ9Iv6PWdpjbybn/550k0h1HZw0tcyZOUT2wRNyyLSVQS0za9hBWquAwkbZtHqntcH/tr/zQDKHmesPAphM8YPWycPpKNz+NpEStfOmIdOKrmeHoZW2G+S+NuA2f5hcgGN6EwE83pJL/iOZW5CH0TVYWVeVJifJuw/RbA7JtIuVuzMwgvzFdQH14iYvSUso7NOXKXORYvxXTm+D4RZ9QjgGcp1luHWFv+1ST0/mBFF9Ktjp1CTBsjAGboyYXl+TDhW1agz/rb5FZtoFy0mGAjID6Ca2L2UjyMAIYikvA6KiIW0y0+s+ShT1xFm3L/JtNMSuMUd+qg2U3GXifBAK9RenwoDQQynZR93fe/XvS+8lyzRKJjJgzAqWAZE9SOQR7+fTTdMmCYxZl689ei/6pTffpjYA1QMbofJEoFjE5KpfEARXVisVLXfCtVIu1iO7GV7P40VVRzeW5XjJmK6Ii9Lwmd4fMe0sPYu31vrggXYfijlvpNyaAFgMSOIMezPsk6Vu/OHiyux3bFo7aGSkUwHNkk6cEKv84Stfjf4YqVEgb1Tb
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: octavia-rabbitmq-password
      namespace: openstack
    type: Opaque
