---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: heat-stack-user
  namespace: openstack
spec:
  encryptedData:
    password: AgCrhv0qZMSkO7I2zHRdYgYwy5MkHTNNoMeX75S+sG8U1cwt9C7GgP4ApktH87V4hD7U3X6Gn23SriX4CGV2WwLlL7rjGUYtNlAuDLG9+C7+tz/dpzkSWwQZZUrqkSfbmD+L1gXEf2Q/9W0gqNjNB3SzL6y4/I+fIRyebVnXQjAdLXlUug50IVSDmmrYByl9XvK/k/wU5IKnLN63UotkOyX02WDPs3EjkJXhki/lusmZuKda9phl2HCHtSn/MvLa97QhItGsQkf8kVHuuu3DfdU+g5+rlGYOyjGOT/bvx/KWbRyZejVs5Vk5ZuBhfCxK+79iNe97b5Pg2qxwg29jbM0RYTtdJOAhzaz8ROaVmzqQix+LT+hzVYLuySdcDvhp+ih7nwyLs3z3fVxCU4+Vq3+VfgrEQwX1JBvEyD+l2VQ8j81OyuRG29Xe3nExZiwhd563eNble1mQZSPjxaYM8ZnlT0jQd9zz1xv54Z9TdHWquqzulTkEiAZlNOHKK6JJKHo6FLdToUdve/AwAK+Z9dN/pK8MCaXrljRQ5lqjraHEUNg8bdb4YJIFbBGIaUvHk1R4djLT81qTBntEGlmfalplbcPiVU9EKCLinXLMRW1A5MaCKRXAcjAR13cL0XFlWigi9Eidj7pj3kNeUPX0jdKIL1a/JPHPnmS4APP5wRgrxl+I55FwC+tcCOQdpUSd0tm4MfLCQUB6foWOpjMWfqeOA28GtJu1KyI1lo5mEP09IA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: heat-stack-user
      namespace: openstack
    type: Opaque
