---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: heat-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgBVLCkIshNfFkvspGSEnbaD9RQVndTdIgzuafsFiIdTUgt3Va1igBZCr7s3YJFaBzeAnyL5/9cOtILUQZkBjcW1RD6t3eV+xvgNgVqnOT4uHROQF25nTFGz2PK5p7abs+GdgTgLxNm7Uf5fm3tYio8dY2h2DqWTHc+2mqp2h/oCykyXzTlkP7x01DYxZ6IxqUB5gh+NeMgyqby18apOZhZRoDSLISlKhf9o+I7ilICk82+tUHbTClo/b6PF9bElwjllN7i3SX74jK0vYBXOpZT4zcpHZQiaHJo7/5oph8S4G+gMbKXxfEqwkEcmgLBuU23+xd4ikxJznyMZ1RKbimQXi24wWJYhuJF1WfQNdq3LqlnZUgH5xaAA9QG0lxdIfnAI04Q1uxNX66TPb2xGmVJvHpgRN4UBnqyH+BgI9vsjpnTy2pVMQMDuSNEH37zPCv0LBIGKTmGejFQNiTZxkz4ZgH5qllcHoH1Qrba4OXuKfVlMwLCSGEVZcc5yIYAR6GCjH73XrD4tFSUYmSHpEI1biBL9ezmR/DHEkEyPKX2n5yYAgSJex9zFJtXWZWay0piWpHJW41kAMtJlawjXmDokNDYi2sQoUSLopUqObUx+6HUd4iv8KZHbxZsjY36E4oabw9vmYg1JEaEflsPyXNRZVXW8w1HI8rpbkYr7rwC8zPL84X1RcsD/m0Mn7epR/v08q3PcECMh5yqR+oZqWLZTRAZB8AVYAdd+n0v95ZK2ZQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: heat-db-password
      namespace: openstack
    type: Opaque
