---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: heat-trustee
  namespace: openstack
spec:
  encryptedData:
    password: AgA49+2MHn0f6krIjDlsEMsFHGSU5BmoOvTX/F/4k2dv9pzHQ5NsxAT02k+NtbOcBVjHrS09v9XlKuzMV/xjGxb0nQKVBC3TiIAx3GV81adswcFQCTpshFEKLFsRcSXjXjXu9zcJcgTE0dpG8+gGrDvPAGlDyEz2mMXHnkhNNEBCNF95GaJ4qAjO0eN32j2S0BY/9Pfvp1WFbZr+nXmtdMIvuVBIL4twOz3aVZvSK+wTTZI53bD6x0NMe84dUgYBqtE3qPfR4Flsrfxckp1kfETDFO2U6W8L91fW+fLWoGk1q+oEWBkVIuF98lvGNO75CYdm+K1J+AwLKW4LtgqfTFJ6is3I3KVz+vJg5OTbIgsYibBEHHLstnPuMIg+mXdB3Oow6iYj4LzmLq/pNtHmm43xhQd8EcpGDUhq7OLn1spquffYE8rTzU+azPIoIDqL5EBpGEXrh7xiU+5Ei3+oN+qwGFMHOc8wCWIBvcP9NuS+eLbnSPxgDlowz4tPF3vm7KcLfo5NrGhiSpmX9U4AH9FmY2CefZAVR3YpQ7VFvCgihQHCyjUJbjmm5vkwO2ILAWlSpAONVoXqe4CRSeky/VC1vqS9CW6pTcurbw8rzvia9NdLmwU6i0dGcCW9QCM6q7vryqystLw52+XTcqnIRULTIcbsbpfyyHgtj94I5FLw+JheMFlp3JvglBQbbOVvepmKJXWmrqoptktpCTERWiwokcbSxfe8xBE11OlMFV+zog==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: heat-trustee
      namespace: openstack
    type: Opaque
