---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: heat-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgCnhY99UlGhakigpEYGyeO1/LMmwoU7fVollxbdhdvbGURmyB6h5mJTQxwfLskB/GLbGUK2uaiEgtgPvrhtuEAOThCSS2PiH9/RwlPjYX1p02qW5xZpeUsLgBhWv9gu3+wNEI5s8ms6+PNI9qdc1hzTrOsjCvZsx/xOLh/+9y2aYqFlVk1ZOVNG+8hEpBOr4CmGFGMPq6Sf12huP4NUQG2QBAKYFNyFg5CVotpD7oqBQiYip9hmYoY3nGub/9wtZBM1Y+fBM8WhY+VO1HOESHv17+GEii7kLWWFR1R6JJDqsE4wx8W1popvNXUDNa9yLNJq/nEhuqyww6BCO+vx1BsYm/vHysZnetMkjiUTBbhup36RBX5HW0G7u2j0gUYhybkfkkxGYsOphfXRNzNUMe7sGJRxmnjHxWaA4tqm0HMhfWdGjd4ZmTvwPKljQJ5u1hJ7mibnLsHJL06dC2Nrkln8BJj7Zo/Kc7UEYtx/i7Jp4QgL35TAteUowK9TYGdYf7DvBN0bqm1mwSVBzxPZJEr/DPke2u9EBvHjZI7aaffnclZGmtbP/w6U50pShtJr6H1n7Z0tRDEGEuXqCZ2NOrSTpiBoZyfYORDvIbpr6laXg8ylyxU797mWdHkZ3r04Wd2Yv8NpSgwdJDyhlUUk2B0CCm5IZxArUsD8FOh6gnYh628t5NgpsV4WKCHqjZz3l8KIF0i/6Om4afp795XMoht6o/FuTXcS5+F14b65eU8fcg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: heat-admin
      namespace: openstack
    type: Opaque
