---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: glance-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgAQVg33npQKMrHO95E8jvR1HPvXG4mNK7pSo1C2RY18XwOAlpcrzYlyXqw4d1GIRmHa07gKs7x7sREW9RujEO+EngKNoGaFUCy+b6/iTGlVOX2pE6/1WCYj7185+On3HIBumiDfrW8xudIoZmAdi7qBnBZu3TEB16WF9aUmuB3rv+C7GojesnuZRueMC7+VrwvBFqcqaGKNw4ZUe4t3EOPwfvXprCZuY0WajzeM90uNhAaplA5ZaepYjYS5+QrRRf327MEUSQZx++QS8rpcW9d0YhkKfTCWQeHekWY/oZORdOSdCcLr4elOcFsc3rzdpQ2YGWoI9l1cf2DGWs0pGp9hcJxImqjfkCLSAHsqoj7vENi0aIOT4gMuMEqgBPk3xEv+mV+jlC2t6oJgJBdmN05HlWTGT/g+OmeOjuyPIT8dEcmTKDC465cSPCpGH0MdQqWy64bn8RrjnOYskYIlrE7ZN5wePbF1s14Br3VUe3K2wOGI9YU6lnaoLGi0J5Cs/HW4yWMomPa7NRtAZgaJRaRd9UpHOyEcqRHiZD99jJZZeTnkylQxoZvy3IEcKzzpGcjyZCvq7nT25priDZI39ZUA2ULry2VWonlmghJMAoTFfNOt1pLuNVPrkiJ1Zotlj0iMnBl9fDElsai+xSzwthu6DrnFDV0T6Rh4DECf976zrEIJpwuZqoKWHjnHSJa55b4ck5fBTWq+geDtJHDLnmSpM3YBFrKeDmBTgsgRbLOhSQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: glance-db-password
      namespace: openstack
    type: Opaque
