---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: glance-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgAyn4++AMTWJUgPfROk2rHuTDwJuJQT8s0yGwC5foYnrEsbouhdmUkutkHqZ+vScdcsNE9g1gPeNOL306VLF+vER4lvKOa8PUNWvXAfv5OQsr4AXFlnWPLI4oCw9MVEBv+4jaST3k0ibRrprNirp7GxenVcoPPjMhZoytXS/8QOoi63j6gwH8C583w2lKmBSsacxIkNovzKqirShEs6Be+85slKTePcehQMevGqflL4FrJinw5qpVWPlzA6Bv5uKli4U7PTphNGTZvv84rZsnZfRIJU2PFQXtlQcW7Dhd/Wz2txAbjW+LaK/ZyHIU6cgc5E5oqOMaAnlrTqIJBrtmtt51F5lfZTswhN2xwXa0DBr0YIxP5Xy7rtfwSoy0Kag+54sepjcNxsOkNVyD48pA5LPBKLUyz+MHgi/UqHjN+4t2A1hZzLYwSaqe1d7q2k7ivqBf6UkL5hRZ02yYKwOKtSpTVNDg3gXivWSOvW8BVMEMOoQdAXB/3S5z9z6RiCIik375+wNO+ew/Gf7oMzJqGDicmTg9G5ws2Cf7YznAY2M0vGE8iOeEaJvqN6dL5lQMLE76nl6atOB29EY1ECE3gqoxz0oQJbNhAlSXbhqxFzpdWOT2gthsNAyGQ6N7wRDYK6tR+CGt7Aw3l5W7xCw4+k5nWMC+7nbA+PKtws9Oo16qHtWQ/OdWTubAkRFZUr59CfjRababmPIwvtrP+KDO1O09LxlS3ER0QbmGHUZAQaGw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: glance-admin
      namespace: openstack
    type: Opaque
