---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: glance-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgBEy2OBnH4/5VD9IneWhQzN/4uDjHBZUfltVuUhHVmF7ZVjj+SoaMtYR/+8K14OIqo8bTrmLeD5bJvvW0tXWwWrwKmxphPnSz2Bu31p8zdqJzXXN3XAOctd0s0wSUjrOpo8OvbUc/Wfr7VDKazoFvJVbSAzhJTg7MNwVg8Y+fEI4LUZMdFuAKwybsaRowRDCkxz76F868t5eRtaKOSv+21GLu/+tU4/rexbXxAKGs0D6x0SUHTSuLrV1bRaxboKN8tSG+wVTVib9iKgTT9iYOY2Sn98CT1pvJbca9Sgp/Vx79HOEp6W7iDuvR+kN6E/mZCiiUksQjYt6sFtwdEpSCN45JWdPLbNZTS2oZJXYCOgpMFA0BIEjZx5FPPwcwEs6IZohDUc5V3fywYvb8WdAvTDNPX1M3OCTJ5yPluRb5JhiONXfYsHsYoKAaKKkKx5U8PKHz3y2mC7UTAI7trPxuPzNcBqixqCr9mfA9MuQYt5ifqB4Ovw5PmR/4yQlEB023Xktxxot3k4Uv9hh8yfDwqAtMWMHNX5Rwn2IXgIzF8hkAOxS5C9Tmf0qrJsXuSw3O4d37x6Dl6sVMf4ouUq1drMq8Vq15LYmcWL0VloAhIqTYA6SKKEX0xeAmGH23R324wJJ++oDPsf8/+PieYkUdcW22htsE1/M6dZ+yFD3FXp651OgrOw6LqQ/oAWdgMi6d7BwwuxAXv+arb7tYkvcJwx5L95xYadlkP3WkZk0Nfs7HT22jDHMT53Ock9U4cQiIGvlD1Tx0x+3NvEKJfuOej8
    username: AgBtsHPGarQXWhEPe+ZEGa9D6H4xm2v3wVRw0uoRXiJpRXDr1jyXI7rfA/GhHOa17lJ/c2dBispLnHrDaVarx1uATm2l9sDR0wCkUF9xYAGELK0F57oY/W18Ytjj1jESSXWz77sSnB9oD+W4149OTIKebkc3BLacoJRGxM7LfWZ7wy30k6fdZ6Sfr0A+OrndTIUbcsWDVAk2rOwU55CW7K7bsqY34KfBwHeTSCs2u3jEQq6PpGrRo4WmdBgQNRY08Bw+RdauB5MyJNrE0pWkHzoENq/wjPKnPCi/0gpeUgZSAAyA1FqyrGHutHZPTTSFTODtpOzjQ+zyUMBgFSk5yHM+tI8jbd6jqJHW2TPd5PnWpo5jIbDFkBUwnb7JWAIH0KJzxBYaPk3nvotuFz1ZcXKWw22UuT7bYyLeyaLbsZsn0FPKU+I84vawJaBVbRHvxc+2aHNS5p0cZ54WI5kukwN2/t3zfPL6+0nosvc//t28hTT586PZHCSu3l4HoQQ0dmKGtMul92sFHOCTicFAajUeljekFSm6SUdp/1l/psybbxKujf+ESh5WZFAu/mhmYbPbxdZtWq10HtRW/Ia6SC54nxKAFzG+yTcg9ehdUQFIeIWdFuFsAnYC85X4KKv5qqC77p0kZlqlcBhgIy2UX6Reg1049iuBLY0bhdDfa4BWJd1k3v1RBvfz2Ed0eJXPJGxG7mQNPzo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: glance-rabbitmq-password
      namespace: openstack
    type: Opaque
