apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster
  namespace: rackspace-system
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: osh/openstack/04-rabbitmq-cluster
    repoURL: 'https://github.com/pratik705/trinity.git'
    targetRevision: manifests
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      selfHeal: true
      prune: false    
  sources: []
  project: default
