---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: horizon-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgASGl9g8AaNE7nsY7uBKJGpZHNi4VgvPfWYDucYf/r5gCzbccW9SXpT9MzFoOsu9Wtg1VOzelp5zn3n9wBnks6ozVX5mpLteC10de1nTewjbww/kQU1n/qyZo3m17sxhhfbEC1RBU6us96qdhdKxn6j/vZcWsO9MQRpBWG2eW7af6zUIcM2wLIO0ZqYhJcYnSIbihFa7QSYjJD/8THiqnvPQYNcYHTkD9+x9TEAQE+Rc46fGfmm/ZRaWHV/KGW4lxtAXa+Un2iIUqxa1Wa7TarG8NFG1UFdJae0nYunWx8AJuTHspQx5koudivXHyWh/QxijdrXM2TZeS9hDmNHthK9y0bVjeSMwLxtnkHT7ICmuzVheePl1SxO2xgL2MspL4CmxavuqUiZ0DixP9CYHLV48wWJhJm6JI7uE6B6ohndDgcqzCrfHkRoqjI9ay2Uu1yO77e99TRc9IbJT75BC3EjLYSEvHmwqKoYwn9sNAIAk2U9GRe38pnuLn5DGxZIykW+mG+RxU8Whk6aMwitDiZEG78E/UYuJVPUtHBvNWsF99hG1aWBRyetjkdimx3qpdLQyRMrd03G1M45aHPjcXJxhxbGco8qQ6xCFyMyWJL+N0Z4TPCKHJg5FApjYU8V5nDkBHH/n+nJY26iJ0//bOIeWeGlJaH/oC7Ma8CrQBBbAwoSCSWjz8v6oybj99adSzMICyXRgclbRY2IWqwIhzj6VcJixb0S2yRt5fyAAsBAhg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: horizon-db-password
      namespace: openstack
    type: Opaque
