---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mariadb
  namespace: openstack
spec:
  encryptedData:
    password: AgA9LUd4P41P3LJRJIM6D1UTvOQfbi4+0tgj9rZEBNn/gtBYWJqiinMQNOVs84Iph85WQOnBoaIB5sV4OVuXB/+gY0nhCpYVLFVAgxFsuYQiRZIL8pPLXJbogVrZvix8LD3qSCQKzzKcAIGe766IC5aANfuISrEYMf3CIvPsGCeKR9YpmFS1KOAFzw5zRmH2g88Zq0gubcwrbXJ6U8yG7OI+zSyGZ4yFI++VZHKczzticg6qqOwCDddmDHoHIYPmRI8YBrjxHQ9GAQUURTPpR2KXgJMVmEGJKXfDZ2p9RK9aU5diiua0Xt4z/qX0o3K21d5AvM7AyQgtweEFlqfyxzO6EwSTMx2HW4dD83//d31fEnnOFRzLkY3khumtxv5bjWs9s/cBTUv9PqRKKOS9IQFSqgPyjMtJrtLdTerIxSlYKWybt0IVSg7pxavDeArHaUKdia2HjoaNCxhvIHvrc7hV8V4h2NzIGEZYBMv5oP9V2N/1TY/1bvZOuhfOAJKGoAWom3afuxVEB9lfQDSBOdwxW0agv1imeIOtJIo7lbLJjwTH+RAmL1prcimekF1IvOBGonsCKrc/X7irppgoFHx3M/pHHy1vleZu+JoHlEyEDozcTnF8yJHpwen+7kaWkK6D1ONcfuyQ42daSVcR431Ns3SiWHwhNB2znn1DvJZUY+uwySbOqHPMpLUOTKkq6csOfd2ZTXL7bsqRp6RYPJuIPd0IKqxRyAjRKzbsPf6d5Q==
    root-password: AgBfaZUqyIKn9YATEBqEavFvCPT0lZs08mNh+IYAE7u35RSKUGrEFT46K6+G5KzpHreribB0Rikit/NjsZTNicddVhf0SsmD4czPBVCjsHoDdC7MRCBwJgpsXaim+gZVfgLBOaQ8qvQS8cpSm91t5v0ahcfz6uQNHEWtUn/roGetEqPwNXFbVEW2e3F26pnjElUDQEW3Mv5gLPHXlyETrvdlKVbg6wVLOPnHFpsFaAVNgbwwRVhpipkZDwEJOWaEqP08JRSGG2rSVPqV73MOS1fKNiMDVxli5Ha7jBu7ok2pIbG8dAPcKf+o2wDjgN1c9+vz5pT8RKYWcA+R/pbvFsV9ONYdJ1Offc+xtbw9oyfm5i5wv0kjDD6igLkyK5rQHHcGxf4lyM7QxP67pPwArp3/PpZ84XeGDD/TnKxa+ZfNLzWQdXp279mGZwnAiuKwqawNvFN0rpmUASNTUI6G7Kc6kRQa6vNgfR9cvhZJ/SBlHMZ/rAGlK7cdnIsIjUYAxMSpv99GlCI/qFBQ6XHsq2GKBo65du3Vf8SOGcXXtXnx5oNnXU3HbvUGT4AgmtHHJ8HlAdaRjx+K6SN9pO3uCiZ+97JMigYjK4qUOn9g1WTm/Ekx1/QTvvh47tEO4vFeHdwia1SYmapv+ahDwcMR/nEixvqkw2p+zrVDEPFrA/yRMKoktRs4grEblHx90SwhKd1z3UQ4W2hF9k+Gy/O3YxmcpsSqhTZHxQ3LROJfBVejSA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mariadb
      namespace: openstack
    type: Opaque
