---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: glance-rabbitmq-admin
spec:
  encryptedData:
    RABBITMQ_CONNECTION: AgDBT8gmzz3C2dW0GC2i7//DFv3rZtCQB+Fg0gir8fnXdMoL3ZRTsUswt1DMnVnk6AcnPh7GTaIswniytCAD8yD0TJn66/dnBk00WWQtei1vbRZZGWNUeE0MWVXxxrjeKnXQAbxo3j7B868kKLRmkwvy0MO/g1hTubAsKPtU0sKGqgd7XFHwaB50Mw1EljaVfwyn5yEe2AeMPzpnR3wu66FuUettii8MKCRTr+QHOZP/ZxxxaPxG/H5uxHNZvLnClBpunlN5hBkaNKJyIIiPuj2HrYxEkbqVSqnPQHlGfZxmuZn+N4hWSja4YwoxAZILZxAoflCrMgBOUNrBeJSWNQrFABFjhWTi/Rt0Lu4ErIE9U9gDCp2WERprPF458gOc0MRWzTYstAFX1BBBf/ULkiCHqtIovN+s7hm1IxuuLRpn26xBtf+tA2j8EeqkaODxpHaIt9utJ2t5eY2KCnh0RBVndSnHy4U+u9Xu7whXY3tM6JOK0t0VDb8j7u8uP8YxUVnTrQmolVh2u3j1lPe/O/YauoLvHDBcSB9OxxaSDE5635odAD7WjmXyKVh5wVdqrOKBW0STCq/Vxsos+sD1KT3UWnDkz0qZG6ggV3G+e9Ef/HtN3ly5f3Ntst5V8YHM4no5ahQOUneC+j4MLLPxXdvr0/Lx0buZjNpwD6CCtHXkGXNmhnqei9Lk/c7YyTpqrfCGqivjMftrfnH7TVg7RVXNAkjvAHeJgq9lgAUJ67r66dbJgVMjdvnhSukUOcLtP3YhDivpRUjE8P+ADpPsYAwuoRnhZC06MZnai1CI9TbDuOO9VsTnUf3779NPs4UCjTP+4De/xl9hJqKC
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: glance-rabbitmq-admin
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: glance-rabbitmq-user
spec:
  encryptedData:
    RABBITMQ_CONNECTION: AgCf7Y7YZfMA1hGU99f37qQQVIyDsRnsW0qL7YF3M3ZOMSIx274wuIDhfV6UEDtBlstG4PV3dueBltuf3Wx4jtEDXzph6eN+43UcIs3ElTix9qqIdFvyI740+YkpDlStV9ykiDs/zfZ+mHywPqTQrcdB2C69RjELCx4cxeSeGpAeJSP8Mo8AAFFwEa+Nh/Zkuk6NpQzn3D/OySb2YJAZC8wlE5kJZTgKdyGb48XekSb3kZTYdS47wFbkWwZIV/F1l4FnRkYlHyZvALyAvOE8ZVaVJ/W/PyxLNadVrv8UjyyusA3/AIXQurS0WLBwH9/XZ0FXoenqgpSLqJ5KJG1PvP9pw6TYKk3UxWBsvzB25+eqiQDCn1e6JJPy53hkMTB1E40utPMsuVb3eHER4n6NNUvN2ANSR6GfnTSoROqomj8uTP9FrJMCeHMX1szXJPldKPcPFxnlWsnODzlm8JhHA0P08WfV3fqTqDlFEeSBW1X8PRh7bUUqlcVTpooFdqwTXbyuHyDodYaUE7yPiC7IjBUIVltp+wAs4EtOEqPPrAIyyczPTTP0O0qfUQmS6zwgm+7UIODYSqTzjdN/bU5n08TYm9eW0bgf29HN5vZHp1SrEgFbxl/59pyKLOA5/LUtSkdcU/bygL9FUNGrv6O2C5gwWySgGM6h31L/EUKYUQ7JKy017T9Ge6PPogFHO35x4D4cx3SYr8EypD+CnrjmIJiNx82vMt7sC305TRHvh1fjWOciWbVWO3N+nEi6XTkWOPMvadJFhiUfYleJpuLCP1Hns4falh7E4qQXUZiXwfCBMAV3Yuh7Qvadbcbpkv022Gk4axXkWq5CpA0gotbXF+hZ8JO0m80KgfdWqIJLIKgmG6xOGFT0AGzo
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: glance-rabbitmq-user
    type: Opaque
