---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: glance-db-admin
spec:
  encryptedData:
    DB_CONNECTION: AgB29EbJntqwiY2pvIuXDJAZ1OH5KJ2TIa4TctXOIgQxOP6pUrGpln+9g1u7WT+bE2nW53N4pRRPT85rLYnx9YpYYT68LbagyT4e0IOEizYMSesolMVQjO/IoDcp/hMaD4/4mbFX8dp8e0AvCyZUDvDFgyuzHVVbcvDoHMXdfjM8NYGnyjKBVR8MODw6f/HZyVEn5AxlS4Rc4v9zzH7vxqkSUmSxOvwuNkiKEUbL/HsxWy2QLRaPoJa+QP89eUBE3utUxUgEIQCCb8aPLdGqaA6JavUZ9eR6addIpRc0kSHPbc7wH6P5MBKhMMRBJP6GQKdKrTuOG/12t4wNvszZmqm7XZQvlgSesyj8VHIdmcaJltcKUXwhEe9gpKaJKX3rorYcjbBqONytuoGyHTvVan+dmootKKTcu+3DpiMhuXw0YQXjkG+yO9yt7/haJXKgzxEkieU7/q2nP5QufTaqh6TyZ9lkGfxiTXEL8wvFPsQA5VkS2gMEhFFT6yqRUxC0uxi+23qcOMBZbtuJtLevmAb5gdwFE1KNHOxHXXigWPgxDcWvLn9YnPaOe7WjKSrOYctPHG4ifXiccE+zTZWJ0AaE7kNTfSPx5RP0Ls49wNghOfolKt49CimVx++m33Kxiy4yUotOC254N07tpTuFQo3y1duxBRqUGsMOwokViX+Vpk5NF3XRrec29Q4PJpTULl9REpDdUkGMszBGCKrltNDl6IWW2pC1dV4671VhD20OOwKTS1C/7IrCT12ENbg95FiziGVBz9h2NytG0TtsW4vREh+jnuUNLBA3C7zdFv1w68H2kFMWIWn77/KownZBWzGbfpzafQROeUFxoCi5rR025JRhJg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: glance-db-admin
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: glance-db-user
spec:
  encryptedData:
    DB_CONNECTION: AgDSFTKf/JoZQlenpIO15RaldwcYBvPOEr4PfsQqdUgPIjBnZjAdtw0dmWfQH3JTh1uqhUgqhtYUOrX1sonrRlmrciV8zRpFUCBrOF/fPGvQcjSBITwGTmdwWw/J6JRbauTcoOciydtRVVNXiCp67QXb82UAGlk1yNpRD/HatQkIXZiexZ/qlW30gXfgsgcpcwy8NYs/U7tJ+khBg9AhC2OQPKoaNN2syfKXxU+pCpGcf/MDqXcX9JkBUWKsmV75FARfQ6AmoxMPEn0CIY1NFnH2IzXZzWdi69naiMhT1gWa8ye4ivOohOGrtjVCpX9YAhx+qkolTZdisJ20EU4vc40MZcxjqAIa4IdtZBKpttDYaNhyfsk18pOqtZU742rst2L3yBvL1LIIIsRkkcLOxIBbTw8twr4AdZfer6tApvtd90lGHpK0y6QSPtHXs6gFSeP6rEqIXAN2dAWWs1VF5Eb1tf0026Q2bFfApk3nXeZeAh0ayNZZjMHncBGM0KfH6jOf0ggIFcQ0H5CiSLoAtLjo1T8svhSV5DhC0MSR8ug4P/El2XMn1wZkKV/f/MI/BKmuKTmJ+I+N2D3jM/DWNKeLyFlatd8Er1w+xs09tPoAqH5ZMmFX8pz394Afbrt9JUaw8k3rxcRLun7y13OMag+7Ih5FzJ4T28WCRKmj6usIDK08WCRXAW/NJOuoC8Db6WnogOTMboopwzXpzTU62kRPseK1mbg7NOUgqBxqZk4ABEM1bXVlcNQN0kdm3+Nr7sjeJ3KgeqKSQuZf/cZYsxaRkfUd9qH/OxPybjilsUU704afVusNc1WEyeiSJS1dnzeRxZNrj7N7BniNrT46VXLLdDm5NFRp
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: glance-db-user
    type: Opaque
