---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: heat-db-admin
spec:
  encryptedData:
    DB_CONNECTION: AgDHaZXqd2Cw+iLZi3+seRlroT2b1YDZLhoC+jG6NCU9A97Pz3N0sBuFvoE1TjBNzbgoBnXcYIog4nShBamVzyBqxn9pMkyQeJqYO5XCahzJjAvylWXLWMCJ2Rc2c7uR6PJfYGhsTRr7dtG55qAn9q96GqnvB0CDk2Pny/hbWYUS2FZV570ya0CaVhecZFNhNUTSSyc1vMj7SMKk+LTOLx2/99mNp5nO6l5qD13d+lVn3tdHC0kG1/YNUmiqpm0bSkaWpGwqPwFULF7bTy5G+xTIPD2ewxw92NjNoSOn1bMFGRAU7odbaKh0LOwMWQk8cDGo6UzrRk+cWG81DxKqKPcHYOFy60MkQOdRTuZv4yYRkQxgyBK9ZkPKI4wt9CBnEw5y/BEU1M2GXCDvkpwjNNP3eKLFKUVxvYPR/hwbuZwWGdQEiO3LWNJnUgx88424AJ1S5M9GjrP6480diGVtySae/vxFXvxpJFtMKXl0oIwt6W98frd4KAfQ/063QDxflVWAviJQqQqIHnmiMjk37oMQ0bQt++OMnuLzbVzcFCOok6zKruyrhU5RduR6XXOFU2oXuII1sIvFx4edHKiQyR9FKTDh9KPwNZ+r5200kxS0uS/+CeMi8V9wR9CZUgpywPwhIU3o2iH5QZ5T00yIyBKC1A9pLl9U1mAjir1BKrqfNyQhQZ5lCPxDb8bA3aIUkJsSugJDxSdRNafELi51O2lI1RvZpEmFV68+u5/dWDwukJ16fOFhNWsqISRAxf7P841JiOnfTWVQ41ndsj5nT8rK6JdblGVmv9c4l5eL8yT6suKaYwjWezKe/1jTikfz74YmbWPAuK6OonSKgrOR1+S3uqA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: heat-db-admin
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: heat-db-user
spec:
  encryptedData:
    DB_CONNECTION: AgCSXiOxBPA3a0KFQ1VNpl6hb0tEBZ8s4plgQ0ZHMLbEmSb14mpCVhd2EFhjtz7NQSKN9irsUfdYc57P7xhBLtDo72WPYOiQ5JBtWvzbrR2qf0WMozfR/B++N03E1xqjupZ0R+IpI+LDV34jbOhD/HBpev6ndYlxUDMMXTPUrtE4TFSbJfLRMJsBrn3BxzOiB0tPnfKGMu2aKnidTvVD0MLwibgqc16t2uvP6rsnJ89MCyaR9EMl5cjdiyS5ngM2UhHp+B/VjHn3jUcdYwMMx9oHbunReQB+oDTfY6AhOSBfA+pxN6s+q8DPwIf9InamV+gdbc4wz6crlVIxPlTUivUXA6CAE7xgCxlDmrP+tQodJjQk2Mnglhi+pi+QGhlymrJyFtYzguZ0HQaLiLd1NTV0ohjcjw12aYJjyb36RqsKOPZ/PAZc/jMU9NHUNnZ81kd10bpyUTJyuylsa2auZiIGyUiXf9f9yMM1T2F8Zg3Ibvh6eej3x72q6dhxFRL/ruRSgfAvv6ba3C06rfIhyWIEaVq3NUGW7RiYMrhB0SGApzCd4CqASeyO1m1tK8uCiHKD3EznWQcb/6pPaoO2D2bkS+uk4OA3ko42lXkWSOufuQOK8BbZLRNjxewzDsIwSfXmvbCdddGHHa73ioY3KzYupWY7nEWU3cUGQVo5oFqMmfIWtJDZpF6U8iJKb98WorpLnnk8G7t9/x9HjsKAf61cR9JRucTFR9RJr7AwjhVmWlKXUDsD78BdvXdDcVe5e9UAbK+W9PCjZ0N7wxRX6B0K61O9g0oUo89+oIbkUBs6gm/FFcyFNsiJ3Qog8bXgUEHXWbJzvlRFy0X8f9Kr0luy8r4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: heat-db-user
    type: Opaque
