apiVersion: v1
kind: ServiceAccount
metadata:
  name: libvirt
  namespace: openstack
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    openstackhelm.openstack.org/release_uuid: ''
  labels:
    application: libvirt
    component: libvirt
    release_group: libvirt
  name: libvirt-libvirt-default
spec:
  minReadySeconds: 0
  selector:
    matchLabels:
      application: libvirt
      component: libvirt
      release_group: libvirt
  template:
    metadata:
      annotations:
        configmap-bin-hash: 2b58da14b020539cd99e1575b323059ab3164ab9bfd66d4437ac2478fed1e37a
        configmap-etc-hash: 33540f035051d5b86b7f0fe517d27578c7ab971c1edfd0f1e504086f9b1aeedd
        openstackhelm.openstack.org/release_uuid: ''
      labels:
        application: libvirt
        component: libvirt
        release_group: libvirt
    spec:
      containers:
      - command:
        - /tmp/libvirt.sh
        env:
        - name: CEPH_CINDER_USER
          value: rbd-client
        - name: CEPH_CINDER_KEYRING
          value: AQCv5pdl2gLaFhAAJ0nqlBz+EpHMRnYdu6sqBg==
        - name: LIBVIRT_CEPH_CINDER_SECRET_UUID
          value: 457eb676-33da-42ec-9a8c-9293d545c337
        image: docker.io/openstackhelm/libvirt:2023.2-ubuntu_jammy
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - bash
              - -c
              - kill $(cat /var/run/libvirtd.pid)
        livenessProbe:
          exec:
            command:
            - bash
            - -c
            - /usr/bin/virsh list
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
        name: libvirt
        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - /usr/bin/virsh list
          initialDelaySeconds: 15
          periodSeconds: 60
          timeoutSeconds: 5
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
        volumeMounts:
        - mountPath: /tmp
          name: pod-tmp
        - mountPath: /tmp/libvirt.sh
          name: libvirt-bin
          readOnly: true
          subPath: libvirt.sh
        - mountPath: /etc/libvirt/libvirtd.conf
          name: libvirt-etc
          readOnly: true
          subPath: libvirtd.conf
        - mountPath: /etc/libvirt/qemu.conf
          name: libvirt-etc
          readOnly: true
          subPath: qemu.conf
        - mountPath: /etc/libvirt/qemu
          name: etc-libvirt-qemu
        - mountPath: /lib/modules
          name: libmodules
          readOnly: true
        - mountPath: /var/lib/libvirt
          mountPropagation: Bidirectional
          name: var-lib-libvirt
        - mountPath: /var/lib/nova
          mountPropagation: Bidirectional
          name: var-lib-nova
        - mountPath: /run
          name: run
        - mountPath: /dev
          name: dev
        - mountPath: /sys/fs/cgroup
          name: cgroup
        - mountPath: /var/log/libvirt
          name: logs
        - mountPath: /etc/machine-id
          name: machine-id
          readOnly: true
        - mountPath: /etc/ceph
          mountPropagation: Bidirectional
          name: etcceph
      dnsPolicy: ClusterFirstWithHostNet
      hostIPC: true
      hostNetwork: true
      hostPID: true
      initContainers:
      - command:
        - kubernetes-entrypoint
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INTERFACE_NAME
          value: eth0
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
        - name: DEPENDENCY_SERVICE
          value: ''
        - name: DEPENDENCY_DAEMONSET
          value: ''
        - name: DEPENDENCY_CONTAINER
          value: ''
        - name: DEPENDENCY_POD_JSON
          value: ''
        - name: DEPENDENCY_CUSTOM_RESOURCE
          value: ''
        image: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
        imagePullPolicy: IfNotPresent
        name: init
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 65534
        volumeMounts: null
      - command:
        - /tmp/ceph-keyring.sh
        env:
        - name: CEPH_CINDER_USER
          value: rbd-client
        - name: CEPH_CINDER_KEYRING
          value: AQCv5pdl2gLaFhAAJ0nqlBz+EpHMRnYdu6sqBg==
        - name: LIBVIRT_CEPH_CINDER_SECRET_UUID
          value: 457eb676-33da-42ec-9a8c-9293d545c337
        image: docker.io/openstackhelm/ceph-config-helper:ubuntu_focal_18.2.0-1-20231013
        imagePullPolicy: IfNotPresent
        name: ceph-keyring-placement
        securityContext:
          readOnlyRootFilesystem: false
        volumeMounts:
        - mountPath: /tmp
          name: pod-tmp
        - mountPath: /etc/ceph
          name: etcceph
        - mountPath: /tmp/ceph-keyring.sh
          name: libvirt-bin
          readOnly: true
          subPath: ceph-keyring.sh
        - mountPath: /etc/ceph/ceph.conf.template
          name: ceph-etc
          readOnly: true
          subPath: ceph.conf
      nodeSelector:
        openstack-compute-node: enabled
      securityContext:
        runAsUser: 0
      serviceAccountName: libvirt
      volumes:
      - emptyDir: {}
        name: pod-tmp
      - configMap:
          defaultMode: 365
          name: libvirt-bin
        name: libvirt-bin
      - name: libvirt-etc
        secret:
          defaultMode: 292
          secretName: libvirt-libvirt-default
      - hostPath:
          path: /var/lib/openstack-helm/compute/libvirt
        name: etcceph
      - configMap:
          defaultMode: 292
          name: ceph-etc
        name: ceph-etc
      - hostPath:
          path: /lib/modules
        name: libmodules
      - hostPath:
          path: /var/lib/libvirt
        name: var-lib-libvirt
      - hostPath:
          path: /var/lib/nova
        name: var-lib-nova
      - hostPath:
          path: /run
        name: run
      - hostPath:
          path: /dev
        name: dev
      - hostPath:
          path: /var/log/libvirt
        name: logs
      - hostPath:
          path: /sys/fs/cgroup
        name: cgroup
      - hostPath:
          path: /etc/machine-id
        name: machine-id
      - hostPath:
          path: /etc/libvirt/qemu
        name: etc-libvirt-qemu
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
