---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: libvirt-libvirt-default
spec:
  encryptedData:
    libvirtd.conf: AgAxIOdRxuNvmfmFBwIyPxEC3shu7LhZZnf4RrMrhBAMud9N32jyeTR821tKBFgsZ+985v1xHVTIWYmU7ogLD8QS4AqRYXFUX7ttcNu5J1hOnuzUBzLSUldn8G9+He/j239gEHK3FeMvMroxlGtfqBI/AvgfGV5DlnlKhK4gp6yTWiXN/+EWEV6Zlj06wnHHFGWqrwCtTIjIeUjvaCvUswmokx6V+89+HMz4Nbxjyc9Z++CeRlczIv7fhJrIYRwIros2yEOofSYUJ7pHNJ8r1Y12qnIYn7huDkhKptf5v+jdnAkYvbWF3pG45L7aldcz40lT7Udfyi0E80QqMvw27ICAeepuWBlzcZpgoyYA0ndun7tSKuqf2CeVZLA0v/LzRYeAbhBJUn3r0AILIe9o1lOEb3TJWE8CK8+97Xi4yM4ZDYwEHiYRUE0JctqRluKT+8YFv3aJEfQ6uvHa/a4QZW2BVs6QZtUUHM/xZ48Tug9WRkHUaR5+4V0WtrGgkZBxXCMBAiQ14Es+ct0yCf9KX2/y0MpdgZ45brWHquiORuNxpe8YjYlXZLBR6hpA0NxsCqtk+g+eqw4DJOX+s8P3qXJPnq/vDaGjXCxzmKh+oVxZTr13MSya68bISC4hwMZ6okVkoqsGxA+N58zImETZxTWqNtW1EKOOmBB5hWMc7viSGzaXKy8Dst4yN1PvmuP2g/yj9Q2w5txEozehaYRx1o7/RAhGz8zh3PVQR/zUkc9IKtZA7AXlnVx+sqd8PKNRdy809EirmdDKSaEYWPzN6SrmEFoXBkzLEDZbZEB3xq4tcgWYjJUv2jVUb6WgUNUjyutaXYOKw346HNkPD+SRz968439j/snFkg7yole6NrXW7QlMsF3cgXbzUtPfKzxEvLQMx4D4oeptKVIIG47Yf6LUBhKVJvwbw6Hk47wzZSQnnOTNUC1RbG2lEU33xtnwZi6b7MXhzoAVQ0vo2VcFLdyWgk7/A0tx4nLUg3qY5L+gEaB17TPoUDngHVl5nCAOTNSywLjz3RUiNRuVQacA7U7dQDvTk2+rlKK45Zm8PsC8AUgg3KfGlSdLZLKJIgSEqjKGULh4k5cDIA==
    qemu.conf: AgArC0rLPxfWYzBMPdNnY7KOm4D4ewqDBUQtuewuvzC7TfV5Lj65RtDE/6LI0HDtFHjINLPWssTaHeIn5j3/5KVgHLU76575Q5TCsPigZ22qE/1KPl+v3JqfDVH3ongZr0FJnydrYuki26sgH/0AA+l26o5K7OwzEMPkWva4qH9t/9kgvUnjBs3p7UaTGLvZqcB2cdcsNDMRyOEgm14fn0cu8vlVkPkRj9odussfZOEyCcLLTFRbmMwsVc+IFf2k4Srar7T37l6OKlvXvufBhda/ln1sOFdTf+cy2VwAmZJ93X7MGTmS2bJ6rVdDwF0diDoTHQNAxKMYmzmA6W8Un8ilCKmRk55LIUl3Hpz27n72ep2itDpcIKoNsgCGw2lvOJIqkU4jfj9qwRZUol+jnHpWagxlmei4fQw1RSzTPOtlC+GrdYJdTq4dBZlO7Q9SdyAQnCSKlnFR/otypSHI8Hl2o7BdwzfDs3DKc5AFC0IxyJ4QWXxEn5EzyVnA02bc7YUY71TL3WGlRFh03HHHUB1uqGrbOlDfvD0P9pThQZZQaWqtNBEET5qi8YrDhnzgBTMQzOLCUj73AXZvxZZH9u7uy8hsXRdtP7u9MyJwC909ZlOgTlTTBjoB6dq7yBBeLUvB/XlNC9Wtp5odRqMMoCwtGQnb9e3odpR3ZTLqAy04RryLREZvXKr2Lekb2BbQdK2mAUCA6kCIXR+d/mlwi68hpI2p4b3DVHJ77HzTQtmPpuTz1t8a44m+qxodGntoVyjg0pGmCSUwsdOWIwxbxghuS4md9E1CMt+PDNs/dA4R3mQuVdvPcFU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: libvirt-libvirt-default
    type: Opaque
