---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgBFmaiU6DuZFhqfoywrnQeVZOO0UcSV853J5rPhs0IqfuHPq+E3YyzTIWW3liAPbaOMspzBCHVwIdsvPe1N46qkCjVnRSPFph/gokA89R7xjWK21rFN3tZzAxK5MfdQ2V7D7xx815fg/6QbsBeZ4BbEq2Hn1iY5q5AJobuROg3Gc7lKRGfRRyJJnuuRLCBNGqmHDqLrCqkWpKkgZQOZ5+U+kKfL4Gd0j2f3haWHQ5BTuoUEQ14X6hYAcesGKPWAr0J7G63/53BVSNl2lf/dNcHwVonvR0V4ehUzfe8Oj0mV6Vel2SFb9+w8iSs8nlkst8JGGSSHiBgGajtGzif+SGjReL7mwSyvieekWs4wL6sz81OVhbj8pP3ea/+qmCwjd2Typ7z03ahe4LxFdxQ36JVxy99Ix3gSVgfB8UFaVOPTYVy5ZstD5UGbxfMIS6fSWT0mvfEot2axmTGa5RVRlJ1SUAkyexByzNSjxf44+zkqIa/YpcRjEDfXxOqjZdbSbpHC4d9vQAErbiK514tzqBtvYRsJ3lG8w0hr09uHNiB+WEcaEqeQjSy9/DjRvdHyXxD5DbiHdIxJJ9Yjj+IoiL7PnH4K7xA+pPdI41CLSzW/RhU0cg14lpZ4iapWv5ppBGVSVxpUaIzaKSkiT5YPqErt4XMS/zJvkGnRXjWuzNCOm7KIPMZsHRZPUguaGR3IFisNvbolwp2319IchghzkPEKc+IRGMTU9SDxl1D03FmhQb+UogL3Y+4r2EEAF6cmwxywdBrdCgs/9j8VqGwRIDeA
    username: AgC8TeFUgHZ8echcMvPnfuPJBbdnqAd681Vlr2twSgSLq+Klx/s99sKd/fLZ0ddaWBNhK34q2p2qMsUxfeXIOgy+HbPj+eVNyB7vIvd/zZ/sLzp6dPXHMfxYqlT1+PlFezWnbRIarNxw2yegJfCDsRTvq20i7gqK0gapY2Kz7J/cGjFzeAVv6hUNB13ubuGcFw9OsIAkLMWgFs16sXAgzvRlazdsQYPJhCFpN9HKTwxNImk1g+sLpqD1vGQXpN1EoTjZh3vzhO28vv4nsHmTgbYwyc9gHbcnrGqKdhYI4Uri1rwhb22uYDDu3BqrHis+wi5TXGeB4wXpt6fcdZc26qwILNlbNUjRoHYEOmMMEDzdX9MgMYbtjmlPVW+d0cFNZYWG/8mqPoCEnSOy1WGhgzG8BurEzg/81EU9A0YWsff4s9ksjYApBHHoLbtaVElS3OGkS67lzbHOgRI2mH+Hx2q6YghrckRHtMqs6IwYr+bJv8xOLIH3SpgycE6GFVacPL1xxA1soKDN+S5fZf9yGLhh0RvxQGuFMQqr27OsCKI6Ck15WC2omuHg/iRe63dyuoc+oiMQbkPBvrsu1gpBCWgoDoWyMyyijYS1zGcKvwUZBn0ADgmBNstca37kVtyyG2FHPGSOUO5mGFx//mrsAIsv9hW6y1yverLgDlFnmZlhHZzY3UlB//qmOLFWttqJ9EtAnjB9Edpjww==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-rabbitmq-password
      namespace: openstack
    type: Opaque
