---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgArXMMtVQMmaCknxxo1zqfVwKIaoD+rYKxmhyge4Hindhbx67DVnfa2OUsQvSnI7wqieZCML8O3pqaqTNBmE/seUk51yyc5ZIdrx38N5rNQ8A0MEKj+DUaoiKVbOfMSbx8EC1JANQvpory74y6ZGLsgjTBC5h7DXNl0WcoVE5CuQGh7qLHhhbysyfthnzORcg9bUntubnEzuQpukUwXBgZds3rE9OPgh/1YvUFBSjuchcw/qflDtZPh/lji9GL32HurXvXZosI4ncSmoJd1H9WS+RfeUQjrIHh+x6WNMf8cCWeyCEo0sMITNzDOgxGIKZU4nZIgfo/kjgbMfGxpkuruZLPCGSjrNHhan9FqB96AT2K0muZXJloyNtyd9OQbOQVp2jLBPLbDY+hjkIiPkBrx2U6fi72fmGVY3rywHZhXQ+1EjMbi5cOF0Tqyp4n/gT13s2vV1rSe/vDqp1Yc3MLsxuLcSq6oN4wD7T+4bri3lhEZGrwaOLyeO+bmJLYknwi3NlC/yhnirA/lPufSJZ65uUVqOqSkfOyGTbtj6h2eGf3IPzfkc/WDtv+jh5+8Fyo4sHVKLjI89Rx3shEaokavVgnxp9spdkX5cCKqduy2xydLctcKT8R84IryZ1GwyQECfUiwQO0WJKjyjZTGgrwsFLOJQZFiEKz00/hR87naw+ooe+0Dft5T+etpRMO86oILghiO2M7LFpRJcHgs5Fe+wdkay8RXCc6pC1tNdbzgCQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-admin
      namespace: openstack
    type: Opaque
