---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-credential-keys
  namespace: openstack
spec:
  encryptedData:
    password: AgAuIQ0bLlJ0nfDj2TNfq0ljqOW/KdwIfnnBecjJDSPdwqk6RqcRAqlcgFGBJd6y+grG8R39uZ2wyatO8kv1O5646m664vp3/Q4rEvRwM7phKcrw8mgy1VcAVaChCFXYhK+YUN98OxGFzT2AVv20yGDjmY9gK7Cd3O5cCZTOzfnQytmVp5lGSLcpf0WWQfZ8QCFdEe8QZYKHk7SPhZAvzKEENi3H4BZm+t3RqPOSdd8aue3dk3v0oapz00fjP86w+jffygjtwE2uY1MzVZj9/FCGQM9FYHrlbaOjmH0FE70qn9+C/N977gjw669UuC6gexYPGjO9oTXHm/88RrKAr3D+sThHy5WmCbsx1V4B56BvqlKlj6ZBOZo9i9L+y579aRbYrDPpBzvRlVMgfcJiCvM575Rv5UCZU2aIuG5xAai1ErP/lfSn6L9vM8Qzu9YHUjh2MMXQ6E7nlnX77f4ooBSrBtUTCoAbadkiWIPE5xbCmKhMkqkTQjh3bKjHT0vBzbq8fyFrCYg8v8afGu8kd21vZ8qJVsRPl3rFk1vtgi4stdzwu46BiXrYOjG+ibcIpljvKit1QIMlI9honJ2jDTZN5vFOFLR//7BRMvjyDfhAnB7WRRlYOZtv7Sek2dyochtMDrHC004BTavnZzzCrwfPQXSu5ibc5ccmpjdnu387sC/Hg/nTFKO1dpwuMpDaSlebMXBvNEIv2nk991wIl/OWzEX0qY0+0M6HmaGXeYGFCw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-credential-keys
      namespace: openstack
    type: Opaque
