---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keystone-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgC64pUCaSL3WMLDyV5DvSCo+9qzJb9WNi9W6oihKNYfi7XsneemDbYKyMYhjIDgKw/6BTwrDPAbTILj9zCW+/HRyx99M/ISYVUaZSAAs1M7dtBgoFSJaFlKj5AhVoTbAACpihOv8MCKY+wTpdxhrslsUCJ/biZRe1uL7HjJL5UkdZ9HrhsXL6m5K0RUpBmRfESED0Ux2DOZx8NIufWMRMK1MnBc1j2uUzRdqwN4E5Grcjlpdy15xwEJSZQpJnoAKv7rhHvqUGyEl8b5ltuTiA+E/PsZ6wSoVc5BdecLw8s3ISHCGC16U6mT4Nd311nOSj2pNkMJ7lu+M0vOsSfuD4rPypWjNrEqfKJEXP7KpmA0TOhzqlSWTycRwwTGlyi5qmDkf9ObsXHsqDtWjNJTYO4lZcYcMKvJdB0sH2RRk5tLlHs7+u/TioTHK3Iy8bY/T6NHjuWHM6AXJOwniBA6AyiPM5OR9gMHNJU4Qsh7uRK3Cvoxf6Hf3jyYAuZ1Qv8DaXTycOHZy9yTV2M3sj6lEWEfQsx2UueHsiQLs5KpsME6uIZ1WG6RALEtG4jhYnnaZFms1ybZYyeXZmgoNL41ZOo4gGFHRgSkxAqZQPigTChxI/z4n+9B0pLurQiK+bPC5SApXYLycSB3UcSnrRbeVCdSQ/THqsK/TEvmEY+i76NbNVLf8QXqL6KyfYF5zIBa3m+4yux4zRhRJj8Gg1IudQIo1G5xnJkaPvf+RjuqI7aAOQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keystone-db-password
      namespace: openstack
    type: Opaque
