---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: nova-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgCoKe3kjy8/MnPooX+304IZKOvcHDihRjE4WkmmBobyrxwEEMblK2u4kZiLCCNjWnE8iLDMUYFfAp+cnLeKTfCykFDZ8ETdWV3GUU+y3ZKHzPSybDWnNInYeJbR1V8bAvb2tAj9gvzXCxRCXrCZbbnpwmnkj7YK4kp4M9Hahk9n22Nu8fcZCw+CjHhYaBAC/cuVyC9WpdFzW14tJhqxCPMrf/+u6eM/ni/9U0bPdZXRORDdrkPdDXO6g/fkxVB/2DnTYPVaB8IFYlOlXXo9wHZd46pc10yfX4Fn+VEN/UA9YhfVN5XI4t/nocpEiMVJi9u6tVkq8sJvXJpG0i9afF2Bx2BveecJmV7DhSxQ9ZACNymQxCes8NZT+FlEC81oegsM0Y3WzvHNoX7+M0Q73fK571+fVAYqbIzpcN0zR9CJqSt6AnZJoLhOyoGxz+PbbD9h+HbFigQQmyXV0SM7MHF3vA8S2zU/obzxOSDKhf039eR4pktzDep2FcpB787WJf9Hkwk/wNV/cb6zaDV3PMz4xaRYlVlr+U9P+YsK1puZ1OurlpPgqUB+RVsuB1yMrqXtiG8MsRNKFE+8kRrPO7hcHYHteSNnJIgiYMoLWvseLu8Yp7fCU3WAYBPuF6ROp/AQS/2oj0wigEaAP/XHZczc4NoyTvv7oZaheuh9WV1XEeatplcY/AX6vKU5ns5JqNLRBkdeYwKH2SHNOW15b7xJt4o0KJpsz0qPl7y0/oG53Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: nova-admin
      namespace: openstack
    type: Opaque
