---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: nova-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgDNboL1aDNnA+nRCQzn5eavMqWQCivDjc/Lqpu2sc2coYVLe7uKJOI44dm5ZVKvSeRxWWb0aYKNf3UTf0XiNFnVHrrdeW/kmzZIF9j+Ld2clULOIfp751qpvtibw/klIBPk1vrHPjd2og5GZb/Yca9oCtm8yvIgWuwVVmetif+tBD3EUwbAQ9RcQd6VNmtEPunRvJKuBxsMhgedHhG7tbubkpmTgdKeYdmmuPL0EGhpi5hGIy7kDep8aL1wPhhGejusZl7ZXGPjMeNiJ1oUewpBqjZGxRfqVGcx19N4NkKYPl3EiRvV7BJllLjmq1iZ+LX6HM6fXUB7ZVgOhvhX3h5cox0qoDYUekz6DZttP4R1wbNgxZ3XK+0dko93XQ98qZQaHe06+RzSf4kajM93BnT6RoxLqx2M87Xo88pGqjdR69J2I6JRuOUimprNOe2S6rlkUr6F4HpwdumivZl1B9n/6MJ2ZozgRq59Quik/QKL/TpE2QWVeGPQg2mIUC6tKvq7Tdhz4OgKMTaQuRqJBz/zYSzkK+XhxjGbA7Bpv+W1dPnb4U3FP7fYOz1XB4Rr3UleFHvcQt89eVKWtASuvR78GVrhK3AzxgdrOG5lbb34MkrBeSKTwO3X9TdVo8HJoYSZS29e9PWVpCJVo87cTooZLUkQ6NlK/SSKPNMXYcUy1k4vAfP1AKGt9ruVK+LzKkSf0ZYD16PYsaXLXAPTCX5C3rG8BrlKwtbeTF1Ajupdag==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: nova-db-password
      namespace: openstack
    type: Opaque
