---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: nova-rabbitmq-password
  namespace: openstack
spec:
  encryptedData:
    password: AgC7vjAnjCa89g7lMv0H2VVYCCoaHAgkRjYj488SfvLRTVW8FFV1YjhLR01i5l8O+l5oWaHdP8eeUk2sTX+fJvZnCFJnEz3W8VBhBzLNihPMKlSpPZ/mgPHhnLX7ZCbuS47Sme5eXABpB3f/HNbnuU/aol1/3XySjmWm4WzEH7HDPb7SfnmJdpP00AzU6YdF2t21ptY+rv1BTvYWllhdsrHK7UOxhcyHu0JvWXGh//yaIwIOtDj7dRzdPrXTtvM88SwQFL2LjCI/4pmj5AEKtLsizCWBmv9DCWQaqLx3Au5tRkTTp0i6Ihm/mOJFWrT+IvlcOnaOPxvbCWtgPWeBxBH9J4//uy0EsLlZXzDA5yw5pYw6t4XyfusvoQjXeIgALiB9RX1/03eEGGnWkfc5aiuYrLm9iuMwjK9Y1Zn+ioB4BUK2TS8H5KxOU4jZXtyQ4DKtBT63Yu2tlrr+z3L8DyVL9aBR/VeVRPJ6cqTrzAK4Y+f53QB300UxKr8+IgZV5WklvBLkcdOozehYG4E6tYuHzE+NGYbXIpb53DY0HCU4iGUbPUpJpM1EhM+Z5/5+QynLQyIfLGtxVp4gfYISOwi6bF5sTyIxdbkzdRJQxl13iK7crADC6kUq0/bUODr7uSN6MmjpqA1WpxGXhOQxDcnyHaeaWjykcwIW8eshO94tNNs1B/FlGEMKc3LHoCe2I5baCD3aMFmyTLo2QLEuueEXAAzbTJrceaqJXSfFI2HdZIcWi2b+0TLI++ucgjgyU4TC7ntdiPPAiyBKKDgOROaB
    username: AgBkt71MAICKkeRMwBcsb/VL5EyUUmscmAyJn/qZdpSzhGITS3tSCErdiZ13yP+vCfy+8Kfcs0/HSvpJNqBKqB9TYkZ/TZgmF6LFdCC+C3iXIB5R0r2/3OLkGzQVNTu7iCVvGyZ7BodFfLGSvDAjWN1uF0v9Zq7jRJ394Aif6n+8OTtuZh+Mo0+QMxyTAWKvXBtUAJ4YmHYR9mLgVBFiURYd+uR9zV6cPUqTNL6mbeEXt5+ZRG0sOc3wVjPPZuOhWkbE1lat4YtFSI74gF9oUW5R3ke0WjnWEjms8b+kfAE5oOROS4U9HzSZh3uOPAcDsZwxKwzHQZcO6toYbSb2Kk5lP63x5sbmvwHoz6uGxBB8XVTTJ9YdJsE3wUXg4yIgIrsBx7M45z9zAzqpPCErW7ItC4SyK/CS5unywv3oRh61QDRLGqrYi8QPlYCa7ykeC9pjSM3ATDV/r1cRBojNd4F5RLO6U5CPGLJkQAU+CEyhN+svHkkD9oE0jHUjhXwpVUCJmHUsZLs3leQuzYzWt+7kU/Ta44Z8+5WCAQWz8D6r6AVr8mas/W3xkbMH004rK16oxmrN/BuVbKN4h7zrYNVr6gwzVWl6wpQIlL9DTXuPBwmNMJrjdtPd37+8LvlwXoBKCELGEw0qiK8yuftJgZzU2LUlya+XeqfcMLl80Lnps+BQqS4i8+sCKKsQBXVcs9mJQFs9
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: nova-rabbitmq-password
      namespace: openstack
    type: Opaque
