---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: rbd-client1
  namespace: openstack
spec:
  encryptedData:
    key: AgASkzXXGHdPL3ClYa3usSGg7UnFNZ1MrYpRLLOyJ17lYl7ISx4L7ocIkIuvNDjmLtNi97fm2ZlqsURVoejT6/GggJz84qb4LvghtVZIlBI1GVKsWSY8eLk19lMDqK2AWA7urcObqaqAjcNRzqg89Ao0zDhZVKGVUV/i6C8YD+FzIIsa5Ma9ZELsLDp91ZVqPHv+4f+PntkF5a9HXiJxK5ithr4W+/SpcN/y3fCRUuNZrj+7te6N1BytJU0E+ZfZSoS6eWWm+/n4giKD3slAf+ZIAwMPKbWXQnUVhqVvmrF8z1zecxFi5nQvb5OgJiRquKG+wTGNy94Wgtnld5a5xLwreKPLOLIfB2eGI10ibETObDaXAZ/A7zuI1D+4ONSvQKizuqbKdD7o2mHBDcvR/A7wrHOAr80R8AF7Cuph0iuX2Hfo6nBYP52JHHkWfTgTp7qZ8bub8gUjUS7xzR1yUUlFPtGDStmYJtrtl+BWSkGKJoBR1e+qL840nEF6hKLGiUr3b2hj9z3B3tnM/S/HwMtV+/7wKB3hiJIKpFJ2x+G7qARfS1eriuahHvJPXZsSExLeWVqjHXboWqnUPq4fJjfrCo03e2XX9xpjgaUALd+Oqws7tBe8MZvyGlbbLxU3sP7KCMkScYacbzqKmNL0zCHClNDC2UXVXALPCCRLYqRwhhq+J0gQbT0AH4ZMcaJJsC1ZylZS394cpVQezYdZNDtxbOnVuWLqPU5dk4lM+73ty5PyUHO9jA0Q
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: rbd-client1
      namespace: openstack
    type: kubernetes.io/rook
