---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cinder-db-password
  namespace: openstack
spec:
  encryptedData:
    password: AgCgWEmfp8wln8RXCxBi5wfHBtYlsfIDXN9VQe+X19jbGRCJrBBf6l5jW0iheMzEhBTpaC/g9+4Z0Omj3YwoYlPGjYQOQIb/Alt+mctr9TEjH1yBPL1P7LFyeBwtA/EPLPK4I3JtsxwxTEDZtT7/UHHcbM7kHCtugMbSbsMdAhrplXOkiK7OIUMFW8nM/va11ZEPhhQVqVxlbrLApEvQkIu8l5Vv46FdDzh+p07d4ZawFJiZG3WwgDEvIWmCSN+IIHuuwLuCq8CcQdTGEcKPbTQR+k5n12vcEjk5oCZW/Q8uiZZ+stcM3zJJennguf/QiIg9HQunNlfKX5SmhetxyBmX+z0MPnfh826MjHZuegYFkw64pqs4fUICzrdS4xyYSJS1NdWxdmKuaoA8CJk5VfW910TO/JggRWMROPSEYAmcvva7Ro9ISXvPqGlFAWkoSnrBWGZpf+za7+r6Oq8ONDNUVLV3OWbdTJlIYBDXdlxc6N36JI7hCXPYrg4eDAVrq7tqY9TlEb2zv3t/gsPjw97tcymu8SAPjK/X2+ytnC6R6RgdJpIc3eW2u42JOeZMa3kchaOiNiyMsLthK4P7PumlfomJsoDF9Yu8pEieuv9sQAxWya/b24RP01dFMcrEf/zPoQHm7bLfCvF6cYbjtQyY3DyrhCBdOaAEppUfw5CfNNWHTInWkf7bXiUDXPyYTxDtC+QMz8V5l5461KadN4OwjP5deL9EvQsUz6B8YC7S3g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cinder-db-password
      namespace: openstack
    type: Opaque
