---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: designate-admin
  namespace: openstack
spec:
  encryptedData:
    password: AgA33XXGNfMVPbjVDK3R+T7r6jW0ETMqk2zkPXDz7TshiEVGZE0ADerqYFEy7BGn8P8aAjynAne/qWOcO3anTfOpLFckcD7Sym7ez7ERzNmxEN20fZ3slb5pghS3t9PT/GkCeroSkT2gHGyhGBxRnn0myFh3aY5hM21TspKTUcX7MEBuj0b1o+ffQg1XohwGDxUQ2axf1eGqeiEAeM/XT7PKxrAIkNzdHxktL6LDhN/rHuLfrf9xCuftp1B5Dy0NCtDMCUcj1WTr4i0QqFwzTZ/BL1j0XnkJ7PR+lzjCWJSMPKHL120cXKRwk8jbCpcC4kX78K+Z2PTN6ri27kOoEwIT9C+48f+HyKoUgdJjaLm1sFDkyB8Llwdiho4tp3FFJKDqXz4yQCfZCupz3krLVADBrmxWgvovGfszBUfFX/MAJRl9ah/evNUU6ulEv4jWX9/lQmvUViIHSi+w8HhBqPh5axpPVKL8famc327bCFFDfTTSQJmuKH28FqldlRrI1H9aZ2YOdsLBaUx/YIWMuygC3bZ7YNjRTdoKjrxOzaK4SOCqLECqyz8yF+d4GUNCnTFdBEWnPcLy0Qfucodf4ouBR44n0DC1sxTR8hl9KurhbhQPySemoaMMr5HezEp2Dy70dBheE6y19EgEw7DOVNweMzXWts7gKs3MxNADIhG1gIofuWru1iW4Y31CZqZTiN6EOESblilBh7gVkLd09wHmsDIIFOd6t5KG85laDAg1pA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: designate-admin
      namespace: openstack
    type: Opaque
